unit Config;

interface
var
	ConfigFileAreaWidth : Integer;

procedure ConfigInit();
procedure ConfigImport(Path : String);
procedure ConfigExport(Path : String);

implementation
uses
	DOM, XMLWrite, UserInterface;

procedure ConfigInit();
begin
	ConfigFileAreaWidth := 20;
	ConfigExport('pfm.xml');
end;

procedure ConfigImport(Path : String);
begin
end;

procedure ConfigExport(Path : String);
var
	Doc : TXMLDocument;
	Root, UI, Key, Comment : TDOMNode;
begin
	Doc := TXMLDocument.Create();

	Root := Doc.CreateElement('Config');

	Comment := Doc.CreateComment(UnicodeString(' Config generated by PFM version ' + UIVersion + ' '));
	Root.AppendChild(Comment);

	UI := Doc.CreateElement('UI');
	Root.AppendChild(UI);

	Key := Doc.CreateElement('Key');
	Root.AppendChild(Key);

	Doc.AppendChild(Root);

	WriteXMLFile(Doc, Path);
	Doc.Free();
end;

end.
