unit Config;

interface
var
	ConfigFileAreaWidth : Integer;

procedure ConfigInit();
procedure ConfigImport(Path : String);
procedure ConfigExport(Path : String);

implementation
uses
	UserInterface,
	DOM,
	XMLWrite,
	Sysutils;

procedure ConfigInit();
begin
	ConfigFileAreaWidth := 20;
	CreateDir(GetAppConfigDir(False));
	if not(FileExists(GetAppConfigDir(False) + 'config.xml')) then ConfigExport(GetAppConfigDir(False) + 'config.xml');
	ConfigImport(GetAppConfigDir(False) + 'config.xml');
end;

procedure ConfigImport(Path : String);
var
	Doc : TXMLDocument;
begin
end;

procedure ConfigExport(Path : String);
var
	Doc : TXMLDocument;
	Root, UI, Key, Comment, Node : TDOMNode;
begin
	Doc := TXMLDocument.Create();

	Root := Doc.CreateElement('Config');

	Comment := Doc.CreateComment(UnicodeString(' Config generated by PFM version ' + UIVersion + ' '));
	Root.AppendChild(Comment);

	UI := Doc.CreateElement('UI');
	Node := Doc.CreateElement('FileArea');
	TDOMElement(Node)['Width'] := UnicodeString(IntToStr(ConfigFileAreaWidth));
	UI.AppendChild(Node);
	Root.AppendChild(UI);

	Key := Doc.CreateElement('Key');
	Root.AppendChild(Key);

	Doc.AppendChild(Root);

	WriteXMLFile(Doc, Path);
	Doc.Free();
end;

end.
